export const defineMain =
`// This file is auto-generated by tools/generate-ast.ts
// or "npm run gen-ast"

{{defineImports}}

export interface IVisitor<R> {
{{defineVisitor}}
}

export abstract class {{baseName}} {
  abstract accept<R>(visitor: IVisitor<R>): R
}

// The AST classes.
{{astClasses}}`

export const defineClass =
`export class {{className}} implements {{baseName}} {
{{vars}}

  constructor({{params}}) {
{{assignments}}
  }

  accept<R>(visitor: IVisitor<R>): R {
    return visitor.visit{{className}}{{baseName}}(this)
  }
}
`
