// This file is auto-generated by tools/generate-ast.ts
// or "npm run gen-ast"

import { Expr } from './expr'

export interface IVisitor<R> {
  visitExpressionStmt(stmt: Expression): R
  visitPrintStmt(stmt: Print): R
}

export abstract class Stmt {
  abstract accept<R>(visitor: IVisitor<R>): R
}

export class Expression implements Stmt {
  public expression: Expr

  constructor(expression: Expr) {
    this.expression = expression
  }

  accept<R>(visitor: IVisitor<R>): R {
    return visitor.visitExpressionStmt(this)
  }
}

export class Print implements Stmt {
  public expression: Expr

  constructor(expression: Expr) {
    this.expression = expression
  }

  accept<R>(visitor: IVisitor<R>): R {
    return visitor.visitPrintStmt(this)
  }
}

